# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='group',
            new_name='groups',
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200, verbose_name="The song's title"),
        ),
    ]
