# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singers', '0002_auto_20161017_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='groups',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
